name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 下载仓库代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装 PyInstaller
        run: pip install pyinstaller

      - name: 打包 EXE
        run: pyinstaller --onefile --windowed lock_timer.py

      - name: 上传 EXE
        uses: actions/upload-artifact@v4
        with:
          name: lock_timer_exe
          path: dist/lock_timer.exe
